network:
  version: 2
  renderer: NetworkManager
  ethernets:
    all-eth:
      match:
        name: "e*"
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
  wifis:
    wlan0:
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      access-points:
        MIRU_5G:
          password: "miru0110"
          auth:
            key-management: psk
